# Generated by Django 3.0.8 on 2020-07-28 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Maximum length is 255 symbols', max_length=255, verbose_name='Account name')),
                ('api_key', models.CharField(help_text='Maximum length is 255 symbols', max_length=255, verbose_name='API KEY')),
                ('api_secret', models.CharField(help_text='Maximum length is 255 symbols', max_length=255, verbose_name='API SECRET')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Account',
            },
        ),
        migrations.CreateModel(
            name='ClientAccountCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Number of connections')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitmex.Account', verbose_name='ClientAccountCounter')),
            ],
        ),
    ]
