# Generated by Django 3.0.8 on 2020-07-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitmex', '0002_auto_20200728_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccountcounter',
            name='task_id',
            field=models.CharField(help_text='Maximum length is 255 symbols', max_length=255, null=True, verbose_name='Task_id'),
        ),
    ]
